### ISSUE TITLE
Unable to play midi. I think the program isn't switching octave

### ISSUE THREAD

**Issue by BeaverP** [parulina/bardmacroplayer#11]
Trying to get this to work, it seems fine, but I notice even with the test song you've given, the program doesn't switch octaves in-game, unless I'm doing something wrong. Here's the file I'm trying to play.
[song.zip](https://github.com/parulina/bardmacroplayer/files/1962518/song.zip)

Parts of the song does play at -2 Octave, but I can't get the rest to play. Lemme know if I'm an idiot or not.

**Comment by pixaline** [comment]
Did you experiment with the octave shift slider?
1.2 may have some issues regarding parsing keybind data. So please try the [pre-release 1.3 version](https://github.com/parulina/bardmacroplayer/files/1901693/BardMacroPlayer-1.2fixfix.zip). The upper slider of the two on the left is the octave shift, try playing the song and moving the slider up or down.

**Comment by BeaverP** [comment]
Seems to be working now, thanks for the new version.
