### ISSUE TITLE
Keybind bug in 1.3 preview

### ISSUE THREAD

**Issue by ghost** [parulina/bardmacroplayer#15]
Only alphanumeric keybinds are recognized by the program. Binding notes to anything besides 1-0 a-z will result in the program skipping those notes. There is no known workaround because there are only 36 alphanumberic keys and 37 ingame notes.

**Comment by pixaline** [comment]
What symbols were you interested in using as a keybind? I have investigated this and found that the game uses its own codes for non-alphanumeric keybinds, which i'll have to manually map to proper keys.

**Comment by ghost** [comment]
Just the symbols next to the numbers and letters which don't include a modifier.
, . / ; ' [ ] \ - = `
Full keyboard mode is broken until the issue is addressed.

**Comment by pixaline** [comment]
[BardMacroPlayer-1.3.zip](https://github.com/parulina/bardmacroplayer/files/2143649/BardMacroPlayer-1.3.zip)

Here, try this version. I added the keys `` =,./;'[]#`\ ``.

**Comment by ghost** [comment]
Thanks for fixing this!
