### ISSUE TITLE
Playing multiple notes simultaneously

### ISSUE THREAD

**Issue by guitar1560** [parulina/bardmacroplayer#16]
Hi Parulina,

First off I just want to thank you for making this awesome tool! It's really fun to play around with!!

Now, I've been going to some websites that let you download sheet music as MIDI files but most of the music is composed for piano/other instruments that allow for multiple notes to be played simultaneously. Since playing multiple notes at the same time is impossible in FFXIV at the moment, do you think it would be possible to implement some type of feature that allows for these multiple notes/chords to be trilled upward rapidly (ex. a chord with A, B and D would be played in that order in quick succession)? The macro already kind of does this but sometimes it will take preference to some notes over others or only play one note out of a whole chord.

Thanks!

**Comment by pixaline** [comment]
Hello, apologies for late reply.
This is something i've discussed and thought about how to solve. Detecting chords would be rather easy, it's just the decision on how to play them. Going upwards as you say sounds like a good idea, so i'll probably implement that in the sequel to this app, which is replacing this one, as it's too difficult to maintain in this programming language. Thanks for the suggestion, i'll take it in to account.
