### ISSUE TITLE
Some Notes not registering

### ISSUE THREAD

**Issue by Vorcan** [parulina/bardmacroplayer#19]
First of all outstanding work you have no idea how much fun I am having with this. I am no musician so this tool is perfect. Again... Thank you

Some MIDI files that played perfect on the 1.3 version are missing some notes now and then on the 1.4 version. Nothing that important but just pointing it out. 

Thank you VERY much

Vorcan

**Comment by pixaline** [comment]
Thanks. 1.4 is a bit bugged, so i'd recommend using 1.3 for the time being until the new app is out, which is a completely new program. Look out for it.
