### ISSUE TITLE
Korean server

### ISSUE THREAD

**Issue by sunnyboycho** [parulina/bardmacroplayer#22]
currently ver 1.2b and 1.3 works on the korean server,
we do not yet have the expanded keyboard setting thus making 1.2b or 1.3 optimal.

however one common problem i've been faced is that
though the normal notes are being played, other octaves
shift and ctrl are not being registered.

i want to take a look at the parses (check if shift and ctrl are being registered)
but i can't seem to do that (either blocked or my lack of knowledge)

any fixes or help? please?
i believe the korean server will also have to use 1.4 after the expanded keyboard patch.

**Comment by pixaline** [comment]
Hello, apologies for the delay. Could you please share me your KEYBIND.DAT?

**Comment by sunnyboycho** [comment]
i'm not familiar with these files
i don't understand why i have a dozen of these files but i'm sending all of
it

i should hold the KEYBIND.DAT you've asked for.

if it is another file, if you could specify which one it is i can always go
digging for it.

these files were in Documents -> My Games -> FF XIV -> all the files there.
for your reference.

**Comment by sunnyboycho** [comment]
[FFXIV_CHR004000003BC10105.zip](https://github.com/parulina/bardmacroplayer/files/2273826/FFXIV_CHR004000003BC10105.zip)

**Comment by pixaline** [comment]
Hmm, that looks normal. Is the program finding your character data?

![image](https://user-images.githubusercontent.com/6361957/43933776-feda76e2-9c4b-11e8-897a-704cb7beac68.png)
![image](https://user-images.githubusercontent.com/6361957/43933788-0b266eb0-9c4c-11e8-8fb6-1c41a4d8b5cd.png)

Please share me full screenshot of this list.

**Comment by sunnyboycho** [comment]
hmmm. that's interesting.

never thought it should have something other than "automatic"
might it be because my language setting is in korean?

![default](https://user-images.githubusercontent.com/23292774/43941650-e438c168-9caf-11e8-9dab-d7c1ca5122a8.png)


this is the same for both my desktop and laptop.

**Comment by pixaline** [comment]
I think there is an issue with finding keybind then. Please share me the full path to the folder where your FFXIV_CHAR* data was. In my case, it's:
``C:\Users\paru\Documents\My Games\FINAL FANTASY XIV - A Realm Reborn``
Perhaps on Korean systems it is different.

**Comment by sunnyboycho** [comment]
![image](https://user-images.githubusercontent.com/23292774/43942038-6909efce-9cb1-11e8-9061-1a8d5582e650.png)

C:\Users\SUNNY\Documents\My Games\FINAL FANTASY XIV - KOREA

**Comment by pixaline** [comment]
That is why. In the code, it assumes the "normal" version, "FINAL FANTASY XIV - A Realm Reborn", not "FINAL FANTASY XIV - KOREA". Here is a Korean version, please try it.
[BardMacroPlayer-KOREA.zip](https://github.com/parulina/bardmacroplayer/files/2278867/BardMacroPlayer-KOREA.zip)

**Comment by sunnyboycho** [comment]
problem solved!!! my god you are an angel.
all txt files and midis works perfectly. it detects my character file with no problem at all.
thanks a lot for going that extra mile for a dude on a remote server :)

**Comment by pixaline** [comment]
Cool, enjoy and please look forward to the sequel, Bard Music Player (#23)
