### ISSUE TITLE
Sharp notes always played one octave too high

### ISSUE THREAD

**Issue by Kurthys** [parulina/bardmacroplayer#24]
Hi! 

First of all thank you so much for Bard Macro Player and all the hard work you're putting into it and its big bro (hopefully) soon to come!

I've been toying with it for a few weeks now, and I recently realized that the sharp notes are always played one octave too high on BMP for me for some reasons, making a lot of tracks sounds a little to very off and clunky depending of the amount of sharps. 
I tried lowering all the sharps from a track by one octave using Online Sequencer and it suddenly played correctly IG through BMP (but ofc very off in the midi itself).
Everything else is working properly, and it's not THAT much of an issue since I found a way around it but I must admit that having to tweak every single sharps of all the songs I want to play by hand can be quite time consuming haha!

For ref, I'm using Bard Macro Player 1.3 (but I have the same issue on 1.4), my game client is installed in French (maybe it can mess with the binds?) and as I said everything else is working as intended.

Thanks in advance, and thank you again for BMP! So hyped for Bard Music Player :+1:

**Comment by pixaline** [comment]
I don't provide support for the macro player anymore, as noted in #23. The new player has more proper code to parse keys and play back notes so I would recommend to just wait for it. Other than that try resetting to default keybinds, I can't help anymore, sorry.
