### ISSUE TITLE
Midi input support

### ISSUE THREAD

**Issue by pixaline** [parulina/bardmacroplayer#3]
Had a thought earlier - since the program already parses the keybinding information, and provides a way for midis for playback - why not add support for midi input devices as well? Currently, you are required to download something like [Bome's Midi Translator](https://www.reddit.com/r/ffxivperformances/comments/7u3u8s/patch_42_is_out_heres_how_you_can_get_your_midi/) and set it up with a specific keybind file.

Quick googling made me aware of [midi4ahk](https://github.com/micahstubbs/midi4ahk), it seems relatively easy to set up and use, and would only add an (optional) dll file next to the exe.

My only problem is that i don't actually have a piano keyboard to hook up to my computer. So, i could try and implement this feature, and anyone who has a midi input device could try it out and report bugs.

**Comment by pixaline** [comment]
OK, added basic support midi input at 0be02d0 and 03ca199. I reworked the interface to add a selection menu and added some other stuff as well. feel free to pull and test, i tested with a basic virtual input device, so in theory, it should work fine with your piano.

**Comment by Nerdorable** [comment]
Hello. I'm sorry if this is not the right place to comment as I am new to this site, but I wanted to thank you for making this wonderful tool. The separation of tracks is especially useful.

I had a request regarding midi input. The test.txt contains notes/composition for a song with input parsed in a way FFXIV understands. Would it be possible for the tracks generated from midi files to be exported into similar text files that we can edit and use separately? Some midis are a bit off when it comes to their timings. If we could edit the compositions your program is generating we could make them much more accurate.

Another request I would like to add is a tempo slider to compliment the octave slider.

**Comment by pixaline** [comment]
@Nerdorable No this is its own issue, please create your own issue for feature requests (button in the top right corner).

I can say that the original idea of midi playback was to only let them play, but i've thought about a way to convert them in to bard arrangement files. However, there are a lot of ways to interpret midi files and combining the tracks. It could be done with a lot of experimentation but i'm a bit busy nowadays.

As for the tempo slider, that could also be done. I'll look in to it.

**Comment by Delequiox** [comment]
Hi Parulina. 

Sorry if this isn't the correct place to post this, but I'm using your application and it runs great. No Issues. Thank you so much for your efforts.

I had a question regarding midi format compatibility. If I use a midi file from let's say MuseScore for example, it works just fine. However if I export that midi file after I've tweaked some notes in a program like AnvilStudio I get an Unknown Event error. Is there something I'm missing here on how this application reads midi files? Thanks in advance.

**Comment by pixaline** [comment]
You should submit an issue of that error message with the big green button on the top right.

Closing this issue.
