### ISSUE TITLE
Midi not playing properly

### ISSUE THREAD

**Issue by galgamack** [parulina/bardmacroplayer#7]
I've messed around with a midi making sure it's just 1 note to make it simple for the actions to go off but it seems that when I hit the play button it play's 1 note and then starts typing in my chat?
https://onlinesequencer.net/import2/846cfd7aa8ea9b24492bafd8325b2958?title=SecondDreamPerform.mid

As a sort of separate issue I ran into while trying to input the same notes from the midi as a text file the notes started off working properly at first where -1 octaves worked but then +1 octaves did not and were parsed as regular C's or D's without octave changes.
[SecondDreamTest.txt](https://github.com/parulina/bardmacroplayer/files/1862155/SecondDreamTest.txt)

**Comment by pixaline** [comment]
Does App > Parsed keys show the correct key configuration layout as your in-game keybind?
For example, this is my (default) setup.
![image](https://user-images.githubusercontent.com/6361957/38122537-eca4fa9e-33d5-11e8-9639-89d389e0e3e6.png)

**Comment by galgamack** [comment]
My app does have the default setup. I figured out that I can just unbind the default keybinds for certain shortcuts it was changing to in my chat box. IE swapping to yell, whispers and previous people I've whispered. that's fixed the midi. well, for most of the notes, I think it's just not playing higher octaves since perform is so limited as to what part of the keyboard we have.

But for the .txt files it's hit or miss sometimes. as for example the test .txt you have to go through all the notes sometimes doesn't change octaves but will still read the notes.

**Comment by pixaline** [comment]
That's because you have spaces between the note and the octave. You should write `C+1`, not `C + 1`, because it's space sensitive. As for the midi playback, you are correct, bard has only three octaves to work with so it's quite limited. Closing.
