### ISSUE TITLE
Shift Slider Issues (BardMacroPlayer-1.2fix only)

### ISSUE THREAD

**Issue by Nerdorable** [parulina/bardmacroplayer#8]
Firstly, thank you so much for adding this new feature! I'm really happy to have control over tempo.

There is one big issue with this slider, which is that it displays a setting of 100%, but plays at a setting of 200% until you change it manually. It does this for every song you play. Stopping a song and playing it again will also cause it to play at 200%.

**Comment by pixaline** [comment]
[BardMacroPlayer-1.2fixfix.zip](https://github.com/parulina/bardmacroplayer/files/1901693/BardMacroPlayer-1.2fixfix.zip)
Try this. I forgot to put the right value when starting the songs.
