### ISSUE TITLE
Bundled songs (want to add your own song to the official bardmacroplayer? post here!)

### ISSUE THREAD

**Issue by pixaline** [parulina/bardmacroplayer#9]
OK, since i've had a few messages from people asking where they could find songs written for this tool, and some also expressing interest in making songs for it, i've decided to open this thread. Any songs submitted here will be taken in to consideration to be uploaded to the repository and the official BMP release. So feel free to post your own songs, original ones encouraged!

* Please only post .txt files for now. No midi files!

**Comment by Nolavakx** [comment]
is there a current list of songs that work i'm having a lot of trouble finding any?

**Comment by pixaline** [comment]
No, this is the official song submission thread. This is to collect songs to bundle with the bard macro player. Right now there isn't any, hence why i'm making this.

**Comment by pixaline** [comment]
Using reddit thread instead.
